
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class BRANCH_COMPANY
{

    public BRANCH_COMPANY()
    {

        this.BUSINESS_RULES = new HashSet<BUSINESS_RULES>();

        this.EMPLOYEE = new HashSet<EMPLOYEE>();

    }


    public int BRA_BUIS_ID { get; set; }

    public int CIT_ID { get; set; }

    public int BUS_ID { get; set; }

    public string BRA_BUIS_NAME { get; set; }

    public string BRA_BUIS_PHONE { get; set; }

    public string BRA_BUIS_MAIL { get; set; }

    public string BRA_BUIS_MAIL2 { get; set; }

    public string BRA_BUIS_ADDRESS { get; set; }

    public bool BRA_BUIS_STATE { get; set; }



    public virtual CITIES CITIES { get; set; }

    public virtual BUSINESS BUSINESS { get; set; }

    public virtual ICollection<BUSINESS_RULES> BUSINESS_RULES { get; set; }

    public virtual ICollection<EMPLOYEE> EMPLOYEE { get; set; }

}

}
