
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class BUSINESS
{

    public BUSINESS()
    {

        this.BRANCH_COMPANY = new HashSet<BRANCH_COMPANY>();

    }


    public int BUS_ID { get; set; }

    public string BUS_NAME { get; set; }

    public string BUS_DOCUMENT { get; set; }

    public string BUS_IMAGE { get; set; }

    public string BUS_COLORS { get; set; }



    public virtual ICollection<BRANCH_COMPANY> BRANCH_COMPANY { get; set; }

}

}
