
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class BUSINESS_RULE_TYPE
{

    public BUSINESS_RULE_TYPE()
    {

        this.OPTIONS_LIST_RULES = new HashSet<OPTIONS_LIST_RULES>();

    }


    public int RULE_TYPE_BUS_ID { get; set; }

    public int BUS_RULES_ID { get; set; }

    public string RULE_TYPE_BUS_NAME { get; set; }

    public string RULE_TYPE_BUS_DESCRIPTION { get; set; }

    public bool RULE_TYPE_CHECK { get; set; }



    public virtual BUSINESS_RULES BUSINESS_RULES { get; set; }

    public virtual ICollection<OPTIONS_LIST_RULES> OPTIONS_LIST_RULES { get; set; }

}

}
