//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS
    {
        public BUSINESS()
        {
            this.BRANCH_COMPANY = new HashSet<BRANCH_COMPANY>();
        }
    
        public int BUS_ID { get; set; }
        public string BUS_NAME { get; set; }
        public string BUS_DOCUMENT { get; set; }
        public string BUS_IMAGE { get; set; }
        public string BUS_COLORS { get; set; }
    
        public virtual ICollection<BRANCH_COMPANY> BRANCH_COMPANY { get; set; }
    }
}
