//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS_RULES
    {
        public BUSINESS_RULES()
        {
            this.BUSINESS_RULE_TYPE = new HashSet<BUSINESS_RULE_TYPE>();
        }
    
        public int BUS_RULES_ID { get; set; }
        public Nullable<int> BRA_BUIS_ID { get; set; }
        public string BUS_RULES_CODE { get; set; }
        public string BUS_RULES_DESCRIPTION { get; set; }
    
        public virtual BRANCH_COMPANY BRANCH_COMPANY { get; set; }
        public virtual ICollection<BUSINESS_RULE_TYPE> BUSINESS_RULE_TYPE { get; set; }
    }
}
