
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class BUSINESS_RULES
{

    public BUSINESS_RULES()
    {

        this.BUSINESS_RULE_TYPE = new HashSet<BUSINESS_RULE_TYPE>();

    }


    public int BUS_RULES_ID { get; set; }

    public int BRA_BUIS_ID { get; set; }

    public string BUS_RULES_CODE { get; set; }

    public string BUS_RULES_DESCRIPTION { get; set; }



    public virtual BRANCH_COMPANY BRANCH_COMPANY { get; set; }

    public virtual ICollection<BUSINESS_RULE_TYPE> BUSINESS_RULE_TYPE { get; set; }

}

}
