
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class CITIES
{

    public CITIES()
    {

        this.BRANCH_COMPANY = new HashSet<BRANCH_COMPANY>();

        this.BRANCH_OFFICE = new HashSet<BRANCH_OFFICE>();

    }


    public int CIT_ID { get; set; }

    public int CONT_ID { get; set; }

    public string CIT_NAME { get; set; }



    public virtual ICollection<BRANCH_COMPANY> BRANCH_COMPANY { get; set; }

    public virtual ICollection<BRANCH_OFFICE> BRANCH_OFFICE { get; set; }

    public virtual COUNTRY COUNTRY { get; set; }

}

}
