//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITIES
    {
        public CITIES()
        {
            this.BRANCH_COMPANY = new HashSet<BRANCH_COMPANY>();
            this.BRANCH_OFFICE = new HashSet<BRANCH_OFFICE>();
        }
    
        public int CIT_ID { get; set; }
        public int CONT_ID { get; set; }
        public string CIT_NAME { get; set; }
    
        public virtual ICollection<BRANCH_COMPANY> BRANCH_COMPANY { get; set; }
        public virtual ICollection<BRANCH_OFFICE> BRANCH_OFFICE { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
    }
}
