
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class CLIENT_BUSINESS
{

    public CLIENT_BUSINESS()
    {

        this.BRANCH_OFFICE = new HashSet<BRANCH_OFFICE>();

    }


    public int CLI_BUS_ID { get; set; }

    public string CLI_BUS_NAME { get; set; }

    public string CLI_BUS_DOCUMENT { get; set; }

    public string CLI_BUS_TYPE { get; set; }



    public virtual ICollection<BRANCH_OFFICE> BRANCH_OFFICE { get; set; }

}

}
