//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_BUSINESS
    {
        public CLIENT_BUSINESS()
        {
            this.BRANCH_OFFICE = new HashSet<BRANCH_OFFICE>();
        }
    
        public int CLI_BUS_ID { get; set; }
        public string CLI_BUS_NAME { get; set; }
        public string CLI_BUS_DOCUMENT { get; set; }
        public string CLI_BUS_TYPE { get; set; }
    
        public virtual ICollection<BRANCH_OFFICE> BRANCH_OFFICE { get; set; }
    }
}
