//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public COUNTRY()
        {
            this.CITIES = new HashSet<CITIES>();
        }
    
        public int CONT_ID { get; set; }
        public string CONT_NAME { get; set; }
    
        public virtual ICollection<CITIES> CITIES { get; set; }
    }
}
