
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class DETAIL_VISITS
{

    public DETAIL_VISITS()
    {

        this.IT_HAS_ACTIVITIES = new HashSet<IT_HAS_ACTIVITIES>();

    }


    public int DE_VIS_ID { get; set; }

    public string DE_VIS_NAME { get; set; }

    public string DE_VIS_DESCRIPTION { get; set; }



    public virtual ICollection<IT_HAS_ACTIVITIES> IT_HAS_ACTIVITIES { get; set; }

}

}
