//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.BRANCH_OFFICE = new HashSet<BRANCH_OFFICE>();
            this.USES = new HashSet<USES>();
        }
    
        public int EMP_ID { get; set; }
        public Nullable<int> ROL_ID { get; set; }
        public Nullable<int> BRA_BUIS_ID { get; set; }
        public string EMP_DOCUMENT { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_SURNAME { get; set; }
        public string EMP_PHONE { get; set; }
        public string EMP_PHONE2 { get; set; }
        public string EMP_CELL_PHONE { get; set; }
        public string EMP_CELL_PHONE2 { get; set; }
        public string EMP_ADDRES { get; set; }
        public string EMP_MAIL { get; set; }
        public string EMP_MAIL2 { get; set; }
        public string EMP_PASSWORD { get; set; }
        public bool EMP_STATE { get; set; }
        public string EMP_PHOTO { get; set; }
    
        public virtual BRANCH_COMPANY BRANCH_COMPANY { get; set; }
        public virtual ICollection<BRANCH_OFFICE> BRANCH_OFFICE { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual ICollection<USES> USES { get; set; }
    }
}
