
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class IT_HAS_ACTIVITIES
{

    public int IT_HAS_ACTIVITIES1 { get; set; }

    public int DE_VIS_ID { get; set; }

    public int VIS_ID { get; set; }

    public string VIS_DATE { get; set; }

    public string VIS_ATTE_MAIL { get; set; }

    public string VIS_ATTE_PHONE { get; set; }

    public string VIS_ATTE_CELPHONE { get; set; }

    public string VIS_ATTE_NAME { get; set; }

    public string VIS_ATTE_COMPETITION { get; set; }

    public string VIS_ATTE_POSITION { get; set; }

    public string VIS_OBSERVATION { get; set; }

    public string VIS_COM_ { get; set; }

    public string VIS_COM_DATE { get; set; }

    public string VIS_PROY_NAME { get; set; }

    public string VIS_ACTIVITY_DESCRIPTION { get; set; }



    public virtual DETAIL_VISITS DETAIL_VISITS { get; set; }

    public virtual VISITS VISITS { get; set; }

}

}
