//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_HAS_ACTIVITIES
    {
        public int IT_HAS_ACTIVITIES1 { get; set; }
        public int DE_VIS_ID { get; set; }
        public int VIS_ID { get; set; }
        public string VIS_ATTE_MAIL { get; set; }
        public string VIS_ATTE_PHONE { get; set; }
        public string VIS_ATTE_CELPHONE { get; set; }
        public string VIS_ATTE_NAME { get; set; }
        public string VIS_ATTE_COMPETITION { get; set; }
        public string VIS_ATTE_POSITION { get; set; }
        public string VIS_OBSERVATION { get; set; }
        public string VIS_COM_ { get; set; }
        public string VIS_COM_DATE { get; set; }
        public string VIS_PROY_NAME { get; set; }
        public string VIS_ACTIVITY_DESCRIPTION { get; set; }
    
        public virtual DETAIL_VISITS DETAIL_VISITS { get; set; }
        public virtual VISITS VISITS { get; set; }
    }
}
