//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities_Visit : DbContext
    {
        public Entities_Visit()
            : base("name=Entities_Visit")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BRANCH_COMPANY> BRANCH_COMPANY { get; set; }
        public DbSet<BRANCH_OFFICE> BRANCH_OFFICE { get; set; }
        public DbSet<BUSINESS> BUSINESS { get; set; }
        public DbSet<BUSINESS_RULE_TYPE> BUSINESS_RULE_TYPE { get; set; }
        public DbSet<BUSINESS_RULES> BUSINESS_RULES { get; set; }
        public DbSet<CITIES> CITIES { get; set; }
        public DbSet<CLIENT_BUSINESS> CLIENT_BUSINESS { get; set; }
        public DbSet<COUNTRY> COUNTRY { get; set; }
        public DbSet<DETAIL_VISITS> DETAIL_VISITS { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public DbSet<IT_HAS_ACTIVITIES> IT_HAS_ACTIVITIES { get; set; }
        public DbSet<OPTIONS_LIST_RULES> OPTIONS_LIST_RULES { get; set; }
        public DbSet<QUOTATION> QUOTATION { get; set; }
        public DbSet<QUOTATION_STATE> QUOTATION_STATE { get; set; }
        public DbSet<ROLE> ROLE { get; set; }
        public DbSet<VISITS> VISITS { get; set; }
    
        public virtual ObjectResult<Nullable<int>> PR_DELETE_EMPLOYEE(Nullable<int> iEmp_id, string sEmp_document)
        {
            var iEmp_idParameter = iEmp_id.HasValue ?
                new ObjectParameter("iEmp_id", iEmp_id) :
                new ObjectParameter("iEmp_id", typeof(int));
    
            var sEmp_documentParameter = sEmp_document != null ?
                new ObjectParameter("sEmp_document", sEmp_document) :
                new ObjectParameter("sEmp_document", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PR_DELETE_EMPLOYEE", iEmp_idParameter, sEmp_documentParameter);
        }
    
        public virtual ObjectResult<string> PR_INSET_UPDATE_EMPLOYEE(Nullable<int> iRol_id, Nullable<int> iBra_buis_id, string sEmp_document, string sEmp_name, string sEmp_surname, string sEmp_phone, string sEmp_phone2, string sEmp_cel_phone, string sEmp_cel_phone2, string sEmp_addres, string sEmp_mail, string sEmp_mail2, string sEmp_password, Nullable<bool> bEmp_state, string sEmp_per, string sEmp_photo)
        {
            var iRol_idParameter = iRol_id.HasValue ?
                new ObjectParameter("iRol_id", iRol_id) :
                new ObjectParameter("iRol_id", typeof(int));
    
            var iBra_buis_idParameter = iBra_buis_id.HasValue ?
                new ObjectParameter("iBra_buis_id", iBra_buis_id) :
                new ObjectParameter("iBra_buis_id", typeof(int));
    
            var sEmp_documentParameter = sEmp_document != null ?
                new ObjectParameter("sEmp_document", sEmp_document) :
                new ObjectParameter("sEmp_document", typeof(string));
    
            var sEmp_nameParameter = sEmp_name != null ?
                new ObjectParameter("sEmp_name", sEmp_name) :
                new ObjectParameter("sEmp_name", typeof(string));
    
            var sEmp_surnameParameter = sEmp_surname != null ?
                new ObjectParameter("sEmp_surname", sEmp_surname) :
                new ObjectParameter("sEmp_surname", typeof(string));
    
            var sEmp_phoneParameter = sEmp_phone != null ?
                new ObjectParameter("sEmp_phone", sEmp_phone) :
                new ObjectParameter("sEmp_phone", typeof(string));
    
            var sEmp_phone2Parameter = sEmp_phone2 != null ?
                new ObjectParameter("sEmp_phone2", sEmp_phone2) :
                new ObjectParameter("sEmp_phone2", typeof(string));
    
            var sEmp_cel_phoneParameter = sEmp_cel_phone != null ?
                new ObjectParameter("sEmp_cel_phone", sEmp_cel_phone) :
                new ObjectParameter("sEmp_cel_phone", typeof(string));
    
            var sEmp_cel_phone2Parameter = sEmp_cel_phone2 != null ?
                new ObjectParameter("sEmp_cel_phone2", sEmp_cel_phone2) :
                new ObjectParameter("sEmp_cel_phone2", typeof(string));
    
            var sEmp_addresParameter = sEmp_addres != null ?
                new ObjectParameter("sEmp_addres", sEmp_addres) :
                new ObjectParameter("sEmp_addres", typeof(string));
    
            var sEmp_mailParameter = sEmp_mail != null ?
                new ObjectParameter("sEmp_mail", sEmp_mail) :
                new ObjectParameter("sEmp_mail", typeof(string));
    
            var sEmp_mail2Parameter = sEmp_mail2 != null ?
                new ObjectParameter("sEmp_mail2", sEmp_mail2) :
                new ObjectParameter("sEmp_mail2", typeof(string));
    
            var sEmp_passwordParameter = sEmp_password != null ?
                new ObjectParameter("sEmp_password", sEmp_password) :
                new ObjectParameter("sEmp_password", typeof(string));
    
            var bEmp_stateParameter = bEmp_state.HasValue ?
                new ObjectParameter("bEmp_state", bEmp_state) :
                new ObjectParameter("bEmp_state", typeof(bool));
    
            var sEmp_perParameter = sEmp_per != null ?
                new ObjectParameter("sEmp_per", sEmp_per) :
                new ObjectParameter("sEmp_per", typeof(string));
    
            var sEmp_photoParameter = sEmp_photo != null ?
                new ObjectParameter("sEmp_photo", sEmp_photo) :
                new ObjectParameter("sEmp_photo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PR_INSET_UPDATE_EMPLOYEE", iRol_idParameter, iBra_buis_idParameter, sEmp_documentParameter, sEmp_nameParameter, sEmp_surnameParameter, sEmp_phoneParameter, sEmp_phone2Parameter, sEmp_cel_phoneParameter, sEmp_cel_phone2Parameter, sEmp_addresParameter, sEmp_mailParameter, sEmp_mail2Parameter, sEmp_passwordParameter, bEmp_stateParameter, sEmp_perParameter, sEmp_photoParameter);
        }
    
        public virtual ObjectResult<PR_SEARCH_EMPLOYEE_Result> PR_SEARCH_EMPLOYEE(Nullable<bool> state, Nullable<int> idBusiness)
        {
            var stateParameter = state.HasValue ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(bool));
    
            var idBusinessParameter = idBusiness.HasValue ?
                new ObjectParameter("IdBusiness", idBusiness) :
                new ObjectParameter("IdBusiness", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_SEARCH_EMPLOYEE_Result>("PR_SEARCH_EMPLOYEE", stateParameter, idBusinessParameter);
        }
    
        public virtual ObjectResult<PR_SEARCH_EMPLOYEE_SELECTION_Result> PR_SEARCH_EMPLOYEE_SELECTION(Nullable<bool> state, Nullable<int> idBusiness, string name, string surname, string document, string email, string role)
        {
            var stateParameter = state.HasValue ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(bool));
    
            var idBusinessParameter = idBusiness.HasValue ?
                new ObjectParameter("IdBusiness", idBusiness) :
                new ObjectParameter("IdBusiness", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var documentParameter = document != null ?
                new ObjectParameter("Document", document) :
                new ObjectParameter("Document", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_SEARCH_EMPLOYEE_SELECTION_Result>("PR_SEARCH_EMPLOYEE_SELECTION", stateParameter, idBusinessParameter, nameParameter, surnameParameter, documentParameter, emailParameter, roleParameter);
        }
    
        public virtual ObjectResult<string> PR_UPADTE_STATE_EMPLOYEE(Nullable<int> iEmp_id, string sEmp_document)
        {
            var iEmp_idParameter = iEmp_id.HasValue ?
                new ObjectParameter("iEmp_id", iEmp_id) :
                new ObjectParameter("iEmp_id", typeof(int));
    
            var sEmp_documentParameter = sEmp_document != null ?
                new ObjectParameter("sEmp_document", sEmp_document) :
                new ObjectParameter("sEmp_document", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PR_UPADTE_STATE_EMPLOYEE", iEmp_idParameter, sEmp_documentParameter);
        }
    }
}
