//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_Visit : DbContext
    {
        public Entities_Visit()
            : base("name=Entities_Visit")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BRANCH_COMPANY> BRANCH_COMPANY { get; set; }
        public DbSet<BRANCH_OFFICE> BRANCH_OFFICE { get; set; }
        public DbSet<BUSINESS> BUSINESS { get; set; }
        public DbSet<BUSINESS_RULE_TYPE> BUSINESS_RULE_TYPE { get; set; }
        public DbSet<BUSINESS_RULES> BUSINESS_RULES { get; set; }
        public DbSet<CITIES> CITIES { get; set; }
        public DbSet<CLIENT_BUSINESS> CLIENT_BUSINESS { get; set; }
        public DbSet<COUNTRY> COUNTRY { get; set; }
        public DbSet<DETAIL_VISITS> DETAIL_VISITS { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public DbSet<IT_HAS_ACTIVITIES> IT_HAS_ACTIVITIES { get; set; }
        public DbSet<OPTIONS_LIST_RULES> OPTIONS_LIST_RULES { get; set; }
        public DbSet<PERMISSIONS> PERMISSIONS { get; set; }
        public DbSet<QUOTATION> QUOTATION { get; set; }
        public DbSet<QUOTATION_STATE> QUOTATION_STATE { get; set; }
        public DbSet<ROLE> ROLE { get; set; }
        public DbSet<USES> USES { get; set; }
        public DbSet<VISITS> VISITS { get; set; }
    }
}
