
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class OPTIONS_LIST_RULES
{

    public int OPC_LIS_RULES_ID { get; set; }

    public int RULE_TYPE_BUS_ID { get; set; }

    public string OPC_LIS_RULES_NAME { get; set; }



    public virtual BUSINESS_RULE_TYPE BUSINESS_RULE_TYPE { get; set; }

}

}
