//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTIONS_LIST_RULES
    {
        public int OPC_LIS_RULES_ID { get; set; }
        public int RULE_TYPE_BUS_ID { get; set; }
        public string OPC_LIS_RULES_NAME { get; set; }
    
        public virtual BUSINESS_RULE_TYPE BUSINESS_RULE_TYPE { get; set; }
    }
}
