//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSIONS
    {
        public PERMISSIONS()
        {
            this.USES = new HashSet<USES>();
        }
    
        public int PER_ID { get; set; }
        public string PER_NAME { get; set; }
        public string PER_DESCRIPTION { get; set; }
    
        public virtual ICollection<USES> USES { get; set; }
    }
}
