
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class QUOTATION
{

    public int QUO_ID { get; set; }

    public int BRA_OFF_ID { get; set; }

    public int QUO_STA_ID { get; set; }

    public string QUO_CODE { get; set; }

    public string QUO_DATE { get; set; }

    public Nullable<int> QUO_VRBASE { get; set; }

    public string QUO_OBSERVATION { get; set; }

    public string QUO_INVOICE { get; set; }

    public Nullable<int> QUO_INVOICE_VR { get; set; }

    public string QUO_PROBAL_CLOSE_DATE { get; set; }



    public virtual BRANCH_OFFICE BRANCH_OFFICE { get; set; }

    public virtual QUOTATION_STATE QUOTATION_STATE { get; set; }

}

}
