//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTATION_STATE
    {
        public QUOTATION_STATE()
        {
            this.QUOTATION = new HashSet<QUOTATION>();
        }
    
        public int QUO_STA_ID { get; set; }
        public string QUO_STA_DESCRIPTION { get; set; }
    
        public virtual ICollection<QUOTATION> QUOTATION { get; set; }
    }
}
