
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class QUOTATION_STATE
{

    public QUOTATION_STATE()
    {

        this.QUOTATION = new HashSet<QUOTATION>();

    }


    public int QUO_STA_ID { get; set; }

    public string QUO_STA_DESCRIPTION { get; set; }



    public virtual ICollection<QUOTATION> QUOTATION { get; set; }

}

}
