//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.EMPLOYEE = new HashSet<EMPLOYEE>();
        }
    
        public int ROL_ID { get; set; }
        public string ROL_NAME { get; set; }
        public string ROL_DESCRIPTION { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEE { get; set; }
    }
}
