
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ROLE
{

    public ROLE()
    {

        this.EMPLOYEE = new HashSet<EMPLOYEE>();

    }


    public int ROL_ID { get; set; }

    public string ROL_NAME { get; set; }

    public string ROL_DESCRIPTION { get; set; }



    public virtual ICollection<EMPLOYEE> EMPLOYEE { get; set; }

}

}
