
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class VISITS
{

    public VISITS()
    {

        this.IT_HAS_ACTIVITIES = new HashSet<IT_HAS_ACTIVITIES>();

    }


    public int VIS_ID { get; set; }

    public int BRA_OFF_ID { get; set; }

    public string VIS_ADDRESS { get; set; }



    public virtual BRANCH_OFFICE BRANCH_OFFICE { get; set; }

    public virtual ICollection<IT_HAS_ACTIVITIES> IT_HAS_ACTIVITIES { get; set; }

}

}
